#Self filter for standard ARGOS robot without gripper
#
min_sensor_dist: .15
self_see_default_padding: 0.0
self_see_default_scale: 1.0
self_see_links:
- name: chassis_link
- name: sensor_head_mount_link
- name: sensor_head_yaw_link
- name: autonomy_box_link


