cloud_filter_chain:
  # Only containment filtering
  - name: robot_body_filter_containment
    type: robot_body_filter/RobotBodyFilterPointCloud2
    params:
      transforms/timeout/unreachable: 1.0
      transforms/timeout/reachable: 1.0
      debug/pcl/clip: false
      debug/pcl/inside: false
      debug/pcl/shadow: false
      sensor/point_by_point: false
      sensor/min_distance: 0.75
      sensor/max_distance: 0
      frames/sensor: spin_lidar_mount_link_fixed
      frames/filtering: spin_lidar_mount_link_fixed
      frames/output: spin_lidar_mount_link_fixed
      frames/fixed: spin_lidar_mount_link_fixed
      body_model/inflation/scale: 1.0
      body_model/inflation/padding: 0.03
      body_model/robot_description_param: /robot_description
      filter/do_clipping: true
      filter/do_contains_test: true
      filter/do_shadow_test: false
      only_links:
        - table_link
        - autonomy_box_link

  # Raycast filter for base_link with more padding
  - name: robot_body_filter_shadow_chassis
    type: robot_body_filter/RobotBodyFilterPointCloud2
    params:
      debug/pcl/clip: false
      debug/pcl/inside: false
      debug/pcl/shadow: false
      sensor/point_by_point: false
      sensor/min_distance: 0.75
      sensor/max_distance: 0
      frames/sensor: spin_lidar_mount_link_fixed
      frames/filtering: spin_lidar_mount_link_fixed
      frames/output: spin_lidar_mount_link_fixed
      frames/fixed: spin_lidar_mount_link_fixed
      body_model/inflation/scale: 1.0
      body_model/inflation/padding: 0.03
      body_model/robot_description_param: /robot_description
      filter/do_clipping: false
      filter/do_contains_test: false
      filter/do_shadow_test: true
      only_links:
        - table_link

        
        
